# Generated by Django 5.0.1 on 2024-02-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
