# Generated by Django 5.0.1 on 2024-02-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_secretary_address_secretary_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretary',
            options={'verbose_name_plural': 'Secretaries'},
        ),
    ]
