# Generated by Django 5.0.1 on 2024-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='Secretary',
            field=models.ManyToManyField(to='main.secretary'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctor',
            field=models.ManyToManyField(to='main.doctor'),
        ),
    ]
