# Generated by Django 5.0.1 on 2024-02-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clinic_secretary_clinic_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('S', 'Scheduled')], default='S', max_length=255)),
                ('appointment_type', models.CharField(choices=[('I', 'New inspection'), ('C', 'Consultation')], default='I', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.patient')),
                ('secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.secretary')),
            ],
        ),
    ]
