# Generated by Django 5.0.1 on 2024-02-14 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_medication_treatment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationsStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('route', models.CharField(choices=[(0, 'Other'), (2, 'Oral'), (1, 'Topical')], default=0, max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/medications/')),
            ],
            options={
                'verbose_name_plural': 'Medications Store',
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.medicationsstore'),
        ),
    ]
