# Generated by Django 5.0.1 on 2024-02-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_medicationsstore_medication_dosage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationsstore',
            options={'verbose_name': 'medication', 'verbose_name_plural': 'Medications Store'},
        ),
        migrations.AlterField(
            model_name='medicationsstore',
            name='route',
            field=models.CharField(choices=[('0', 'Other'), ('2', 'Oral'), ('1', 'Topical')], default='0', max_length=1),
        ),
    ]
