# Generated by Django 5.0.1 on 2024-02-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_medicationsstore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='body_temperature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('I', 'New inspection'), ('C', 'Consultation')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='encounter',
            name='goals',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='pulse_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='respiration_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
