# Generated by Django 5.0.1 on 2024-02-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_encounter_blood_pressure_encounter_body_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomDiagnosisPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=255, null=True)),
                ('diagnosis', models.CharField(max_length=255, null=True)),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.treatment')),
            ],
        ),
    ]
