# Generated by Django 5.0.1 on 2024-02-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_symptomdiagnosispair'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='encounter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.encounter'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
