# Generated by Django 5.0.1 on 2024-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_opened_clinic_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretary',
            name='last_opened_clinic_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
