# Generated by Django 5.0.1 on 2024-02-16 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_clinicuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicuser',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
    ]
