# Generated by Django 5.0.1 on 2024-04-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_appointment_date_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSetttings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=15, help_text='the duration of the appointment')),
                ('max_appointments', models.IntegerField(default=2, help_text='the maximum number of appointments')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('days', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BufferTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointmentsetttings')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='buffer_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.buffertime'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clinicavailability'),
        ),
    ]
