# Generated by Django 5.0.1 on 2024-04-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_appointmentsetttings_clinicavailability_buffertime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentSetttings',
            new_name='AppointmentSettings',
        ),
    ]
