# Generated by Django 5.0.1 on 2024-05-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_appointmentsetttings_appointmentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='appointment_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.appointmentsettings'),
        ),
        migrations.AlterField(
            model_name='buffertime',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='buffertime',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
