# Generated by Django 5.0.1 on 2024-05-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_clinic_appointment_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffertime',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.appointmentsettings'),
        ),
    ]
